$ErrorActionPreference = "Stop"

# --- Check admin ---
if (-not ([Security.Principal.WindowsPrincipal] [Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)) {
    Write-Error "Run this from an elevated PowerShell."
    exit 1
}

$repo = "https://raw.githubusercontent.com/ojaskavathe/dots/master"
$kanataDir = "$env:LOCALAPPDATA\kanata"
$kanataConfig = Join-Path $kanataDir "kanata.kbd"
$taskName = "Kanata"

# --- Install kanata ---
if (-not (Get-Command kanata -ErrorAction SilentlyContinue)) {
    Write-Host "Installing kanata..."
    winget install --id jtroo.kanata --accept-source-agreements --accept-package-agreements
    # Refresh PATH
    $env:Path = [Environment]::GetEnvironmentVariable("Path", "Machine") + ";" + [Environment]::GetEnvironmentVariable("Path", "User")
} else {
    Write-Host "kanata already installed."
}

# --- Fetch and assemble config ---
Write-Host "Fetching kanata config from repo..."
New-Item -ItemType Directory -Path $kanataDir -Force | Out-Null

$defcfg = @"
;; Generated by: irm $repo/windows/setup.ps1 | iex
;; Source: $repo/modules/shared/kanata/hrm.kbd

(defcfg
  process-unmapped-keys yes
)

"@

$core = Invoke-RestMethod "$repo/modules/shared/kanata/hrm.kbd"
Set-Content -Path $kanataConfig -Value ($defcfg + $core) -NoNewline

Write-Host "Config written to $kanataConfig"

# --- Scheduled task ---
$kanataExe = (Get-Command kanata).Source
$action = New-ScheduledTaskAction -Execute $kanataExe -Argument "--cfg `"$kanataConfig`""
$trigger = New-ScheduledTaskTrigger -AtLogOn
$settings = New-ScheduledTaskSettingsSet `
    -AllowStartIfOnBatteries `
    -DontStopIfGoingOnBatteries `
    -ExecutionTimeLimit ([TimeSpan]::Zero) `
    -RestartCount 3 `
    -RestartInterval ([TimeSpan]::FromMinutes(1))
$principal = New-ScheduledTaskPrincipal -UserId $env:USERNAME -RunLevel Highest -LogonType Interactive

if (Get-ScheduledTask -TaskName $taskName -ErrorAction SilentlyContinue) {
    Write-Host "Updating '$taskName' scheduled task..."
    Set-ScheduledTask -TaskName $taskName -Action $action -Trigger $trigger -Settings $settings -Principal $principal | Out-Null
} else {
    Write-Host "Creating '$taskName' scheduled task..."
    Register-ScheduledTask -TaskName $taskName -Action $action -Trigger $trigger -Settings $settings -Principal $principal | Out-Null
}

# --- Start/restart kanata ---
if (Get-Process kanata -ErrorAction SilentlyContinue) {
    Write-Host "Restarting kanata..."
    Stop-Process -Name kanata -Force
    Start-Sleep -Seconds 1
}
Start-ScheduledTask -TaskName $taskName
Write-Host "kanata running."

Write-Host "`nDone. Re-run this command anytime to update config."
