$ErrorActionPreference = "Stop"

# --- Check admin ---
if (-not ([Security.Principal.WindowsPrincipal] [Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)) {
    Write-Error "Run this from an elevated PowerShell."
    exit 1
}

$repo = "https://raw.githubusercontent.com/ojaskavathe/dots/master"
$kanataDir = "$env:LOCALAPPDATA\kanata"
$kanataExe = Join-Path $kanataDir "kanata.exe"
$kanataConfig = Join-Path $kanataDir "kanata.kbd"
$taskName = "Kanata"

# --- Install/update kanata ---
New-Item -ItemType Directory -Path $kanataDir -Force | Out-Null

$release = Invoke-RestMethod "https://api.github.com/repos/jtroo/kanata/releases/latest"
$asset = $release.assets | Where-Object { $_.name -eq "windows-binaries-x64.zip" } | Select-Object -First 1

if (-not $asset) {
    Write-Error "Could not find windows-binaries-x64.zip in the latest kanata release."
    exit 1
}

if (Test-Path $kanataExe) {
    Write-Host "kanata already installed, updating to $($release.tag_name)..."
} else {
    Write-Host "Downloading kanata $($release.tag_name)..."
}

$zipPath = Join-Path $env:TEMP "kanata-windows.zip"
Invoke-WebRequest -Uri $asset.browser_download_url -OutFile $zipPath

$extractDir = Join-Path $env:TEMP "kanata-extract"
if (Test-Path $extractDir) { Remove-Item $extractDir -Recurse -Force }
Expand-Archive -Path $zipPath -DestinationPath $extractDir

$exe = Get-ChildItem -Path $extractDir -Filter "kanata_windows_tty_winIOv2_x64.exe" -Recurse | Select-Object -First 1
if (-not $exe) {
    Write-Error "kanata_windows_tty_winIOv2_x64.exe not found in the downloaded archive."
    exit 1
}
Copy-Item -Path $exe.FullName -Destination $kanataExe -Force

Remove-Item $zipPath -Force
Remove-Item $extractDir -Recurse -Force

Write-Host "kanata installed at $kanataExe"

# --- Fetch and assemble config ---
Write-Host "Fetching kanata config from repo..."

$defcfg = @"
;; Generated by: irm $repo/windows/setup.ps1 | iex
;; Source: $repo/modules/shared/kanata/hrm.kbd

(defcfg
  process-unmapped-keys yes
)

"@

$core = Invoke-RestMethod "$repo/modules/shared/kanata/hrm.kbd"
Set-Content -Path $kanataConfig -Value ($defcfg + $core) -NoNewline

Write-Host "Config written to $kanataConfig"

# --- Scheduled task ---
$action = New-ScheduledTaskAction -Execute $kanataExe -Argument "--cfg `"$kanataConfig`""
$trigger = New-ScheduledTaskTrigger -AtLogOn
$settings = New-ScheduledTaskSettingsSet `
    -AllowStartIfOnBatteries `
    -DontStopIfGoingOnBatteries `
    -ExecutionTimeLimit ([TimeSpan]::Zero) `
    -RestartCount 3 `
    -RestartInterval ([TimeSpan]::FromMinutes(1))
$principal = New-ScheduledTaskPrincipal -UserId $env:USERNAME -RunLevel Highest -LogonType Interactive

if (Get-ScheduledTask -TaskName $taskName -ErrorAction SilentlyContinue) {
    Write-Host "Updating '$taskName' scheduled task..."
    Set-ScheduledTask -TaskName $taskName -Action $action -Trigger $trigger -Settings $settings -Principal $principal | Out-Null
} else {
    Write-Host "Creating '$taskName' scheduled task..."
    Register-ScheduledTask -TaskName $taskName -Action $action -Trigger $trigger -Settings $settings -Principal $principal | Out-Null
}

# --- Start/restart kanata ---
if (Get-Process kanata -ErrorAction SilentlyContinue) {
    Write-Host "Restarting kanata..."
    Stop-Process -Name kanata -Force
    Start-Sleep -Seconds 1
}
Start-ScheduledTask -TaskName $taskName
Write-Host "kanata running."

Write-Host "`nDone. Re-run this command anytime to update config."
